name: Build Python Package

on:
  push:
    branches: [ feature/test_ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download Slang Compiler ${{ matrix.os }}
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        curl -L -o slang-linux.tar.gz https://github.com/shader-slang/slang/releases/download/v2025.19.1/slang-2025.19.1-linux-x86_64.tar.gz
        mkdir slang-linux
        tar -xzvf slang-linux.tar.gz -C slang-linux
        sudo cp slang-linux/bin/slangc /usr/local/bin/
        sudo cp slang-linux/lib/*.so* /usr/local/lib/
        sudo chmod +x /usr/local/bin/slangc
        sudo ldconfig

    - name: Download Slang Compiler ${{ matrix.os }}
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        sudo mkdir /usr/local/lib
        curl -L -o slang-macos.tar.gz https://github.com/shader-slang/slang/releases/download/v2025.19.1/slang-2025.19.1-macos-aarch64.tar.gz
        mkdir slang-macos
        tar -xzvf slang-macos.tar.gz -C slang-macos
        sudo cp slang-macos/bin/slangc /usr/local/bin/
        sudo cp slang-macos/lib/*.dylib /usr/local/lib/
        sudo chmod +x /usr/local/bin/slangc
    
    - name: Download Slang Compiler ${{ matrix.os }}
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        curl -L -o slang-windows.zip https://github.com/shader-slang/slang/releases/download/v2025.19.1/slang-2025.19.1-windows-x86_64.zip
        Expand-Archive slang-windows.zip -DestinationPath C:\slang
        echo "C:\slang\bin" >> $env:GITHUB_PATH
        echo "C:\slang\lib" >> $env:GITHUB_PATH

    - name: Check Slang Compiler
      run: |
        slangc -version

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@033219e2d69dd4d3e873e217eb385fdd4b4438f4
      with:
        version: 1.4.328.1
        cache: true

    - name: Test Vulkan SDK
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        echo "$env:VULKAN_SDK"
        dir "$env:VULKAN_SDK"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build wheel

    - name: Build package
      run: |
        cd binding
        python -m build --wheel

    - name: Test package installation
      run: |
        cd binding
        pip install dist/*.whl

    - name: Run basic tests
      run: |
        cd binding
        python -c "import pygs; print('Package imported successfully')"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pygs-${{ matrix.os }}-py${{ matrix.python-version }}
        path: binding/dist/
