name: Build Python Package

on:
  push:
    branches: [ feature/test_ci ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@033219e2d69dd4d3e873e217eb385fdd4b4438f4  # windows fix
      with:
        version: 1.4.328.1
        cache: true

    # This helps find slangc libraries from Vulkan SDK.
    - name: Set LD_LIBRARY_PATH (ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        echo "LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
  
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build wheel

    - name: Build package
      run: |
        cd binding
        python -m build --wheel

    - name: Test package installation
      run: |
        cd binding
        pip install dist/*.whl

    - name: Run basic tests
      run: |
        cd binding
        python -c "import pygs; print('Package imported successfully')"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pygs-${{ matrix.os }}-py${{ matrix.python-version }}
        path: binding/dist/
